env:
  global:
  - _AGAVE_API_SERVER=https://api.sd2e.org
  - _AGAVE_CLIENT_NAME=travisci-agave-files
  - _AGAVE_USERNAME=sd2etest
  - secure: FkqdIwv3gAn89+KvMc2HLywDBnTyB6ejf3axpAe70KR4hD8OwdHOicf9PfC0HeZfYKJdU2jf/SuBDEu3wkOEn2jP94DO7Pg+/Tm+f3knJNsA+KtZn3Fp8cZsz6jt/KrAeogUl3ZyL8woXBrul2BJzO1HBqy1z5+kMT4XISZbrolE+g5V+5JCIdEtzRZbb4hCg3uq4pMSyZEUTdW3lftUAbHZ7nRcxoWK1bTD3MVKCLf2rg3871jlcdjW30ktZQ3NgDcfu7dR8LnZaTcWkYxdZH91KuHWl95GoUoocNMon4/d/lV+64PKUgMQsx1iHW+oTPmuHklup3RYR1IZqsjjPHf9HLTSqi1KEqoKUMMVDeGnGvKfVKIDlW2WCAaoY2dHh3gKyxuKzFY8ykCNDhpW4TDSYH7BoErAYPXdDXmjyuOiGcihPxz8WB362VxgrwUjHDub6y+Hx75IlP77i+5bl22NmxrV9Fy7aFt9Mt4lNu0665R2shcGHyHu+WZe/daXYGq6UZu+sSSyaO74gwRBvtnMscNHhhVU52S1nDIWd4cOFYN11QmxCb899YYR/90idtDHdeGzbhw8vWZ+x3c0w/TFAPCUHfKYU95uj8DSoSh8Jm5vzWxkPXIH00UoIiB7UZzFVJKhW0Vm4qqVrY0wAHRfek0ep+WCv1rZDDysrOQ=
  - secure: PQgenvuFkHGsYZcZkKebNddgU1GUN1vJvukluyidvPawdEJ9fDKBKaQ5MuFMdEq+I4kiwG7wEhfSMp90bVvmzVdgh9xgd8HN+MbR583e18ng2H+3VEaJhygom/dYEEnt40+Kn6KUckV2ELpArunwipcWGDpLzmLjvLFVgJw6FPXpH1LZe+E7BjGnwrxKd/00KwgyespfA07E1AykdV8IqMuw+fQqmgSR4wT/IaCafYK7SNpruyauMY8muuf3pZThi2YtWzXFqLjZ3ptjNw938Nm1kquCZT/O+4Lth0X4vr3VsxTriOANsJ8EBupvSMtr/lwT23VdCK70ONWqVqVIC4t1RmT0JKJkZRDZ0V/LYWTTxXoRFX2aTcVT3fOMGOR++X0wANec2c2t2An8zILh3Une5ARjcUD9iJpLM9qb8xQ2z1y5eAmstBxko1wMkohjR4Dg4FlJofi0F28I/EhgMA/69UQA4qzLiO2Um7btVrmbSHFV1dRwiaL+zzOuCu1ezFJT42twc7OpcafYgMf3P4GoIQd6vhi/tT5lxNzYFxmjCIbKSbsbKgsNBK9hgzVpnSgXnWaJsa8JWzjRIRF+iJymPvKZqfzRCMuL0aRIudH0bCPHEPnKO7ZXEHkdvfJVmZSkqTrdR+I1W3tD5pyrlQAZs/9JjUWdC8UoaZz1W8k=
language: python
python:
- '2.7'
install:
- pip install -r requirements-ci.txt
- pip install git+https://github.com/TACC/agavepy.git@develop
script:
- bash tests/test_download_file.sh
- bash tests/test_download_directory.sh
